# Generated by Django 5.0.1 on 2024-01-12 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('image_link', models.CharField(default=None, max_length=555)),
                ('title', models.CharField(default=None, max_length=555, null=True)),
                ('price', models.CharField(default=None, max_length=555)),
                ('description', models.CharField(default='', max_length=555)),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Publish')], default=1)),
                ('min_order', models.CharField(default=None, max_length=555, null=True)),
                ('product_id_field', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
    ]
