# Generated by Django 5.0.1 on 2024-01-12 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=40)),
                ('name', models.CharField(max_length=40)),
                ('phone', models.EmailField(default=False, max_length=254, unique=True)),
                ('adress', models.CharField(max_length=55)),
                ('adress1', models.CharField(max_length=55)),
                ('amount', models.TextField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='image_link',
            field=models.CharField(default=None, max_length=555, unique=True),
        ),
    ]
